# Python base image
FROM python:3.11-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    && apt-get clean

# Create working directory
WORKDIR /app

# Copy requirements
COPY fastapi_server_requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r fastapi_server_requirements.txt

# Copy application code
COPY socket_test.py .
RUN mkdir ./templates
COPY templates ./templates

# Expose FastAPI port
EXPOSE 8000

# Start FastAPI with uvicorn (supports websockets)
CMD ["uvicorn", "socket_test:app", "--host", "0.0.0.0", "--port", "8000"]
